controller:
  admin:
    password: "admin"
  serviceType: NodePort
  nodePort: 30080
  installPlugins:
    - kubernetes
    - workflow-job
    - workflow-aggregator
    - credentials-binding
    - git
    - configuration-as-code
    - docker-workflow
    - github-branch-source
  JCasC:
    defaultConfig: true
    configScripts:
      setup: |
        credentials:
          system:
            domainCredentials:
            - credentials:
              - usernamePassword:
                  scope: GLOBAL
                  id: "dockerhub-creds"
                  username: ""
                  password: ""
              - string:
                  scope: GLOBAL
                  id: "github-pat"
                  secret: ""
        jobs:
          - script: >
              pipelineJob('Auto-Build') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote { url('https://github.com/mohammedmusa1/intern-devops.git') }
                        branches('*/main')
                      }
                    }
                    scriptPath('Jenkinsfile')
                  }
                }
              }
  sidecars:
    configAutoReload:
      enabled: true

