controller:
  admin:
    password: "admin"
  serviceType: NodePort
  nodePort: 30080
  startupProbe:
    failureThreshold: 60
  installPlugins:
    - kubernetes
    - workflow-job
    - workflow-aggregator
    - credentials-binding
    - git
    - configuration-as-code
    - docker-workflow
    - github-branch-source
    - job-dsl
    - pipeline-stage-view
  JCasC:
    defaultConfig: true
    configScripts:
      setup: |
        credentials:
          system:
            domainCredentials:
            - credentials:
              - usernamePassword:
                  scope: GLOBAL
                  id: "dockerhub-creds"
                  username: "${dockerhub_username}"
                  password: "${dockerhub_token}"
              - string:
                  scope: GLOBAL
                  id: "github-pat"
                  secret: "${github_pat}"
        jobs:
          - script: >
              pipelineJob('Auto-Build') {
                triggers {
                  githubPush()
                }
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote { url('${github_repo}') }
                        branches('*/main')
                      }
                    }
                    scriptPath('Jenkinsfile')
                  }
                }
              }
  sidecars:
    configAutoReload:
      enabled: true
