apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mohammedmusa1/intern-devops.git'
    targetRevision: HEAD
    path: devops-system/k8s/app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
